version: '3.4'
services:
  frontend:
    build: ./frontend
    ports:
      - '8080:3000'
    depends_on:
      - nginx
    volumes:
      - ./frontend:/app
    links:
      - nginx
  api:
    build: ./api
    expose:
      - '3000'
  nginx:
    build: ./nginx
    ports:
      - '8001:80'
    restart: always
    links:
      - api
