version: '3.4'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '8080:8080'
    depends_on:
      - nginx
    volumes:
      - ./frontend:/app
      - /app/node_modules/
    environment:
      - VUE_APP_SERVER_URL='http://nginx/example'
  api:
    build:
      context: ./api
    expose:
      - '3000'
    depends_on:
      - redis
    volumes:
      - ./api:/app
      - /app/node_modules
  nginx:
    build:
      context: ./nginx
    ports:
      - '8001:80'
    restart: always
  #elk:
    #image: sebp/elk
    #ports:
      #- "5601:5601"
      #- "9200:9200"
      #- "5044:5044"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "8002:3000"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    expose:
      - "6379"
